[fashion]
title = "보그 코리아 ─ 패션"
url = "https://www.vogue.co.kr/category/fashion/"
entrySelector = "div.fusion-post-wrapper"
titleSelector = "h2.entry-title.fusion-post-title a"
linkSelector = "a"
dateSelector = "p > span:nth-child(2)"
dateFormat = "			yyyy-mm-dd'T'hh:mm:ss+00:00		"
contentSelector = "span.fn a"
imageSelector = "img.attachment-full.size-full.wp-post-image"
waitUntil = "networkidle"

[beauty]
title = "보그 코리아 ─ 뷰티"
url = "https://www.vogue.co.kr/category/beauty/"
entrySelector = "div.fusion-post-wrapper"
titleSelector = "h2.entry-title.fusion-post-title a"
linkSelector = "a"
dateSelector = "p > span:nth-child(2)"
dateFormat = "			yyyy-mm-dd'T'hh:mm:ss+00:00		"
contentSelector = "span.fn a"
imageSelector = "img.attachment-full.size-full.wp-post-image"
waitUntil = "networkidle"

[living]
title = "보그 코리아 ─ 리빙"
url = "https://www.vogue.co.kr/category/living/"
entrySelector = "div.fusion-post-wrapper"
titleSelector = "h2.entry-title.fusion-post-title a"
linkSelector = "a"
dateSelector = "p > span:nth-child(2)"
dateFormat = "			yyyy-mm-dd'T'hh:mm:ss+00:00		"
contentSelector = "span.fn a"
imageSelector = "img.attachment-full.size-full.wp-post-image"
waitUntil = "networkidle"

[people]
title = "보그 코리아 ─ 피플"
url = "https://www.vogue.co.kr/category/people/"
entrySelector = "div.fusion-post-wrapper"
titleSelector = "h2.entry-title.fusion-post-title a"
linkSelector = "a"
dateSelector = "p > span:nth-child(2)"
dateFormat = "			yyyy-mm-dd'T'hh:mm:ss+00:00		"
contentSelector = "span.fn a"
imageSelector = "img.attachment-full.size-full.wp-post-image"
waitUntil = "networkidle"